//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milestone2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetail: INotifyPropertyChanged
    {
        public int IDOrderDetail { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> PriceOrderDetail { get; set; }
        private Nullable<int> _quantity;
        public Nullable<int> QuantityOrderDetail { get=>_quantity; set { _quantity = value;Notifychange("QuantityOrderDetail"); } }

        private void Notifychange(string v)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(v));
            }
        }
        private Nullable<decimal> _total;
        public Nullable<decimal> TotalOrderDetal { get=>_total; set { _total = value; Notifychange("TotalOrderDetal"); } }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
