//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milestone2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product: INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        public int IDProduct { get; set; }
        private string _name;
        public string NameProduct { get=>_name; set { _name = value; Notifychange("NameProduct"); } }

        private void Notifychange(string v)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged?.Invoke(this,
                    new PropertyChangedEventArgs(v));
            }
        }

        private Nullable<decimal> _price;
        public Nullable<decimal> PriceProduct
        {
            get => _price; set { _price = value; Notifychange("PriceProduct"); }
        }
        private Nullable<int> _quantity;
        public Nullable<int> QuantityProduct
        {
            get => _quantity; set { _quantity = value; Notifychange("QuantityProduct"); }
        }
        private string _image;
        public string ImageProduct
        {
            get => _image; set { _image = value; Notifychange("ImageProduct"); }
        }
        private string _info;

        public event PropertyChangedEventHandler PropertyChanged;

        public string InfoProduct
        {
            get => _info; set { _info = value; Notifychange("InfoProduct"); }
        }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
